// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzsk0l7HCrYPTws4FGlDmHBkFu-Y6hQn0',
    appId: '1:24002710883:web:7642c5ef7dec1a4a5f1756',
    messagingSenderId: '24002710883',
    projectId: 'whatsapp-58d7c',
    authDomain: 'whatsapp-58d7c.firebaseapp.com',
    storageBucket: 'whatsapp-58d7c.appspot.com',
    measurementId: 'G-JX888W1QCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUCV_WRxRvW4IP6CGUloqzBS4HDKV99Kw',
    appId: '1:24002710883:android:cf5ffa3040e48a2a5f1756',
    messagingSenderId: '24002710883',
    projectId: 'whatsapp-58d7c',
    storageBucket: 'whatsapp-58d7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3siGbAq8_I_Q4UGYtYPGut1gK0HH8vGs',
    appId: '1:24002710883:ios:2c9f85be784d70525f1756',
    messagingSenderId: '24002710883',
    projectId: 'whatsapp-58d7c',
    storageBucket: 'whatsapp-58d7c.appspot.com',
    iosClientId: '24002710883-s0ff7tfaa5s8mh933f486e90q8n1uv6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
